include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "build/**"
    - "lib/firebase_options.dart"
    - "lib/routes.dart"

linter:
  rules:
    public_member_api_docs: false
