name: projac_mobile
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ignore: sort_pub_dependencies
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  envied: ^0.5.4+1
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  http: ^1.2.1
  hydrated_bloc: ^9.1.5
  ionicons: ^0.2.2
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  retrofit: ^4.1.0
  routefly: ^1.0.9
  very_good_analysis: ^5.1.0
  equatable: ^2.0.5
  skeletonizer: ^1.3.0
  super_sliver_list: ^0.4.1
  readmore: ^3.0.0
  page_transition: ^2.1.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ignore: sort_pub_dependencies
  build_runner: ^2.4.10
  envied_generator: ^0.5.4+1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
